version: 1

formatters:
  custom:
    format: '%(asctime)s [%(threadName)s] %(levelname)s: %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: ERROR
    formatter: custom
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: custom
    filename: logs/solis-proxy.log
    when: midnight
    backupCount: 90

root:
  level: DEBUG
  handlers: [console, file]
